/* ============================================================
   sw.js — Service Worker
   讓遊戲可安裝、可離線遊玩。

   ★ 發佈新版本時記得把 VERSION 加一。
     改了 VERSION 這個檔案的位元組就變了，瀏覽器才會察覺有新版本、
     重新安裝並清掉舊快取。不改的話舊快取會一直留著。
   ============================================================ */

const VERSION = 'v23';
const CACHE = 'fishing-' + VERSION;

// 程式碼類資產走 network-first 時，等網路的上限（毫秒）。超時就回快取，
// 避免在訊號差的環境下開啟遊戲卡住。
const NET_TIMEOUT = 2500;

// 全部用相對路徑，這樣部署在 GitHub Pages 的子路徑（/FishingGame/）也能運作
const ASSETS = [
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './js/util.js',
  './js/pixel.js',
  './js/data.js',
  './js/state.js',
  './js/ui.js',
  './js/cutin.js',
  './js/screen-fishing.js',
  './js/screen-daily.js',
  './js/screen-home.js',
  './js/screen-shop.js',
  './js/screen-codex.js',
  './js/pwa.js',
  './js/devtools.js',
  './js/main.js',
  './assets/characters/fishing-idle.png',
  './assets/sprites/mist-lake/ml_boot.png',
  './assets/sprites/mist-lake/ml_can.png',
  './assets/sprites/mist-lake/ml_weed.png',
  './assets/sprites/mist-lake/ml_crucian.png',
  './assets/sprites/mist-lake/ml_bluegill.png',
  './assets/sprites/mist-lake/ml_loach.png',
  './assets/sprites/mist-lake/ml_smallcarp.png',
  './assets/sprites/mist-lake/ml_minnow.png',
  './assets/sprites/mist-lake/ml_smelt.png',
  './assets/sprites/mist-lake/ml_trout.png',
  './assets/sprites/mist-lake/ml_bass.png',
  './assets/sprites/mist-lake/ml_whitefish.png',
  './assets/sprites/mist-lake/ml_perch.png',
  './assets/sprites/mist-lake/ml_catfish.png',
  './assets/sprites/mist-lake/ml_goldcarp.png',
  './assets/sprites/mist-lake/ml_pike.png',
  './assets/sprites/mist-lake/ml_koi.png',
  './assets/sprites/mist-lake/ml_char.png',
  './assets/sprites/mist-lake/ml_eel.png',
  './assets/sprites/mist-lake/ml_sturgeon.png',
  './assets/sprites/mist-lake/ml_gar.png',
  './assets/sprites/mist-lake/ml_arowana.png',
  './assets/sprites/mist-lake/ml_spirit.png',
  './assets/sprites/mist-lake/ml_king_onde.png',
  './assets/sprites/garden-pond/gp_coins.png',
  './assets/sprites/garden-pond/gp_can.png',
  './assets/sprites/garden-pond/gp_duckweed.png',
  './assets/sprites/garden-pond/gp_feeder.png',
  './assets/sprites/garden-pond/gp_mosquito.png',
  './assets/sprites/garden-pond/gp_bitterling.png',
  './assets/sprites/garden-pond/gp_wakin.png',
  './assets/sprites/garden-pond/gp_tilapia.png',
  './assets/sprites/garden-pond/gp_paradise.png',
  './assets/sprites/garden-pond/gp_hikoi.png',
  './assets/sprites/garden-pond/gp_ryukin.png',
  './assets/sprites/garden-pond/gp_oranda.png',
  './assets/sprites/garden-pond/gp_grasscarp.png',
  './assets/sprites/garden-pond/gp_pondcat.png',
  './assets/sprites/garden-pond/gp_kohaku.png',
  './assets/sprites/garden-pond/gp_platinum.png',
  './assets/sprites/garden-pond/gp_ranchu.png',
  './assets/sprites/garden-pond/gp_shubunkin.png',
  './assets/sprites/garden-pond/gp_showa.png',
  './assets/sprites/garden-pond/gp_butterfly.png',
  './assets/sprites/garden-pond/gp_ghost.png',
  './assets/sprites/garden-pond/gp_tancho.png',
  './assets/sprites/garden-pond/gp_king_hyaku.png',
  './assets/sprites/rapids/rp_driftwood.png',
  './assets/sprites/rapids/rp_can.png',
  './assets/sprites/rapids/rp_line.png',
  './assets/sprites/rapids/rp_horsemouth.png',
  './assets/sprites/rapids/rp_goby.png',
  './assets/sprites/rapids/rp_stoneloach.png',
  './assets/sprites/rapids/rp_barb.png',
  './assets/sprites/rapids/rp_bleak.png',
  './assets/sprites/rapids/rp_sculpin.png',
  './assets/sprites/rapids/rp_yamame.png',
  './assets/sprites/rapids/rp_iwana.png',
  './assets/sprites/rapids/rp_ayu.png',
  './assets/sprites/rapids/rp_chub.png',
  './assets/sprites/rapids/rp_spinedloach.png',
  './assets/sprites/rapids/rp_rainbow.png',
  './assets/sprites/rapids/rp_masu.png',
  './assets/sprites/rapids/rp_goldenbarb.png',
  './assets/sprites/rapids/rp_torrentcat.png',
  './assets/sprites/rapids/rp_ghostchar.png',
  './assets/sprites/rapids/rp_flowcutter.png',
  './assets/sprites/rapids/rp_amber.png',
  './assets/sprites/rapids/rp_thread.png',
  './assets/sprites/rapids/rp_king_fuseki.png',
  './assets/sprites/sunset-fjord/fj_bottle.png',
  './assets/sprites/sunset-fjord/fj_can.png',
  './assets/sprites/sunset-fjord/fj_net.png',
  './assets/sprites/sunset-fjord/fj_sardine.png',
  './assets/sprites/sunset-fjord/fj_goby.png',
  './assets/sprites/sunset-fjord/fj_anchovy.png',
  './assets/sprites/sunset-fjord/fj_horsemackerel.png',
  './assets/sprites/sunset-fjord/fj_flounder.png',
  './assets/sprites/sunset-fjord/fj_wrasse.png',
  './assets/sprites/sunset-fjord/fj_scorpion.png',
  './assets/sprites/sunset-fjord/fj_mackerel.png',
  './assets/sprites/sunset-fjord/fj_bonito.png',
  './assets/sprites/sunset-fjord/fj_needlefish.png',
  './assets/sprites/sunset-fjord/fj_grouper.png',
  './assets/sprites/sunset-fjord/fj_seabream.png',
  './assets/sprites/sunset-fjord/fj_cutlass.png',
  './assets/sprites/sunset-fjord/fj_amberjack.png',
  './assets/sprites/sunset-fjord/fj_lionfish.png',
  './assets/sprites/sunset-fjord/fj_sailfish.png',
  './assets/sprites/sunset-fjord/fj_sunfish.png',
  './assets/sprites/sunset-fjord/fj_moray.png',
  './assets/sprites/sunset-fjord/fj_oarfish.png',
  './assets/sprites/sunset-fjord/fj_ray.png',
  './assets/sprites/sunset-fjord/fj_king_helio.png',
  './assets/sprites/coral-reef/cr_coralfrag.png',
  './assets/sprites/coral-reef/cr_can.png',
  './assets/sprites/coral-reef/cr_net.png',
  './assets/sprites/coral-reef/cr_damsel.png',
  './assets/sprites/coral-reef/cr_sergeant.png',
  './assets/sprites/coral-reef/cr_cardinal.png',
  './assets/sprites/coral-reef/cr_wrassejuv.png',
  './assets/sprites/coral-reef/cr_gobyshrimp.png',
  './assets/sprites/coral-reef/cr_surgeonjuv.png',
  './assets/sprites/coral-reef/cr_snapper.png',
  './assets/sprites/coral-reef/cr_butterfly.png',
  './assets/sprites/coral-reef/cr_angel.png',
  './assets/sprites/coral-reef/cr_trigger.png',
  './assets/sprites/coral-reef/cr_moorish.png',
  './assets/sprites/coral-reef/cr_lionfish.png',
  './assets/sprites/coral-reef/cr_ribbon.png',
  './assets/sprites/coral-reef/cr_bluespotray.png',
  './assets/sprites/coral-reef/cr_unicorn.png',
  './assets/sprites/coral-reef/cr_mantajuv.png',
  './assets/sprites/coral-reef/cr_seadragon.png',
  './assets/sprites/coral-reef/cr_prism.png',
  './assets/sprites/coral-reef/cr_shadowray.png',
  './assets/sprites/coral-reef/cr_king_ruri.png',
  './assets/sprites/sakura-shrine/sk_ema.png',
  './assets/sprites/sakura-shrine/sk_can.png',
  './assets/sprites/sakura-shrine/sk_moss.png',
  './assets/sprites/sakura-shrine/sk_ayu.png',
  './assets/sprites/sakura-shrine/sk_oikawa.png',
  './assets/sprites/sakura-shrine/sk_funa.png',
  './assets/sprites/sakura-shrine/sk_haze.png',
  './assets/sprites/sakura-shrine/sk_tanago.png',
  './assets/sprites/sakura-shrine/sk_dojo.png',
  './assets/sprites/sakura-shrine/sk_yamame.png',
  './assets/sprites/sakura-shrine/sk_iwana.png',
  './assets/sprites/sakura-shrine/sk_kurodai.png',
  './assets/sprites/sakura-shrine/sk_suzuki.png',
  './assets/sprites/sakura-shrine/sk_unagi.png',
  './assets/sprites/sakura-shrine/sk_nishikigoi.png',
  './assets/sprites/sakura-shrine/sk_kinme.png',
  './assets/sprites/sakura-shrine/sk_ishidai.png',
  './assets/sprites/sakura-shrine/sk_sakuramasu.png',
  './assets/sprites/sakura-shrine/sk_koryu.png',
  './assets/sprites/sakura-shrine/sk_hanzaki.png',
  './assets/sprites/sakura-shrine/sk_ningyo.png',
  './assets/sprites/sakura-shrine/sk_shinshi.png',
  './assets/sprites/sakura-shrine/sk_king_yahiro.png',
  './assets/sprites/tide-flat/tf_shell.png',
  './assets/sprites/tide-flat/tf_float.png',
  './assets/sprites/tide-flat/tf_kelp.png',
  './assets/sprites/tide-flat/tf_skipper.png',
  './assets/sprites/tide-flat/tf_blenny.png',
  './assets/sprites/tide-flat/tf_stickle.png',
  './assets/sprites/tide-flat/tf_shanny.png',
  './assets/sprites/tide-flat/tf_sandeel.png',
  './assets/sprites/tide-flat/tf_clingfish.png',
  './assets/sprites/tide-flat/tf_rockfish.png',
  './assets/sprites/tide-flat/tf_mullet.png',
  './assets/sprites/tide-flat/tf_eelpout.png',
  './assets/sprites/tide-flat/tf_flounder.png',
  './assets/sprites/tide-flat/tf_wrasse.png',
  './assets/sprites/tide-flat/tf_anemonefish.png',
  './assets/sprites/tide-flat/tf_moray.png',
  './assets/sprites/tide-flat/tf_parrot.png',
  './assets/sprites/tide-flat/tf_pipefish.png',
  './assets/sprites/tide-flat/tf_boxfish.png',
  './assets/sprites/tide-flat/tf_frogfish.png',
  './assets/sprites/tide-flat/tf_mandarin.png',
  './assets/sprites/tide-flat/tf_stranded.png',
  './assets/sprites/tide-flat/tf_king_kotaku.png',
  './assets/sprites/frost-lake/fr_ice.png',
  './assets/sprites/frost-lake/fr_can.png',
  './assets/sprites/frost-lake/fr_rope.png',
  './assets/sprites/frost-lake/fr_smelt.png',
  './assets/sprites/frost-lake/fr_whitefish.png',
  './assets/sprites/frost-lake/fr_perch.png',
  './assets/sprites/frost-lake/fr_ruffe.png',
  './assets/sprites/frost-lake/fr_dace.png',
  './assets/sprites/frost-lake/fr_burbot.png',
  './assets/sprites/frost-lake/fr_grayling.png',
  './assets/sprites/frost-lake/fr_char.png',
  './assets/sprites/frost-lake/fr_pike.png',
  './assets/sprites/frost-lake/fr_lenok.png',
  './assets/sprites/frost-lake/fr_sculpin.png',
  './assets/sprites/frost-lake/fr_taimen.png',
  './assets/sprites/frost-lake/fr_sturgeon.png',
  './assets/sprites/frost-lake/fr_glasscarp.png',
  './assets/sprites/frost-lake/fr_bluetrout.png',
  './assets/sprites/frost-lake/fr_unicorn.png',
  './assets/sprites/frost-lake/fr_iceeel.png',
  './assets/sprites/frost-lake/fr_aurora.png',
  './assets/sprites/frost-lake/fr_wraith.png',
  './assets/sprites/frost-lake/fr_king_kold.png',
  './assets/sprites/fall-pool/fp_flask.png',
  './assets/sprites/fall-pool/fp_can.png',
  './assets/sprites/fall-pool/fp_rope.png',
  './assets/sprites/fall-pool/fp_dace.png',
  './assets/sprites/fall-pool/fp_hillstream.png',
  './assets/sprites/fall-pool/fp_whitefin.png',
  './assets/sprites/fall-pool/fp_bullhead.png',
  './assets/sprites/fall-pool/fp_stone.png',
  './assets/sprites/fall-pool/fp_shiner.png',
  './assets/sprites/fall-pool/fp_squaliobarbus.png',
  './assets/sprites/fall-pool/fp_hemibarbus.png',
  './assets/sprites/fall-pool/fp_torrent.png',
  './assets/sprites/fall-pool/fp_climber.png',
  './assets/sprites/fall-pool/fp_anguilla.png',
  './assets/sprites/fall-pool/fp_landlocked.png',
  './assets/sprites/fall-pool/fp_mahseer.png',
  './assets/sprites/fall-pool/fp_snakehead.png',
  './assets/sprites/fall-pool/fp_bigeye.png',
  './assets/sprites/fall-pool/fp_thunder.png',
  './assets/sprites/fall-pool/fp_veil.png',
  './assets/sprites/fall-pool/fp_curtain.png',
  './assets/sprites/fall-pool/fp_roar.png',
  './assets/sprites/fall-pool/fp_king_gyakuryu.png',
  './assets/sprites/lotus-river/lr_porcelain.png',
  './assets/sprites/lotus-river/lr_can.png',
  './assets/sprites/lotus-river/lr_caltrop.png',
  './assets/sprites/lotus-river/lr_topmouth.png',
  './assets/sprites/lotus-river/lr_bitterling.png',
  './assets/sprites/lotus-river/lr_hemiculter.png',
  './assets/sprites/lotus-river/lr_crucian.png',
  './assets/sprites/lotus-river/lr_loach.png',
  './assets/sprites/lotus-river/lr_yellowcat.png',
  './assets/sprites/lotus-river/lr_grass.png',
  './assets/sprites/lotus-river/lr_bream.png',
  './assets/sprites/lotus-river/lr_culter.png',
  './assets/sprites/lotus-river/lr_xenocypris.png',
  './assets/sprites/lotus-river/lr_sleeper.png',
  './assets/sprites/lotus-river/lr_mandarin.png',
  './assets/sprites/lotus-river/lr_blackcarp.png',
  './assets/sprites/lotus-river/lr_sucker.png',
  './assets/sprites/lotus-river/lr_eel.png',
  './assets/sprites/lotus-river/lr_sturgeon.png',
  './assets/sprites/lotus-river/lr_shad.png',
  './assets/sprites/lotus-river/lr_koi.png',
  './assets/sprites/lotus-river/lr_salamander.png',
  './assets/sprites/lotus-river/lr_king_dujiang.png',
  './assets/sprites/caldera/cd_brimstone.png',
  './assets/sprites/caldera/cd_can.png',
  './assets/sprites/caldera/cd_algae.png',
  './assets/sprites/caldera/cd_alcolapia.png',
  './assets/sprites/caldera/cd_pupfish.png',
  './assets/sprites/caldera/cd_hottilapia.png',
  './assets/sprites/caldera/cd_mudloach.png',
  './assets/sprites/caldera/cd_gudgeon.png',
  './assets/sprites/caldera/cd_killifish.png',
  './assets/sprites/caldera/cd_hotcarp.png',
  './assets/sprites/caldera/cd_venteel.png',
  './assets/sprites/caldera/cd_basalt.png',
  './assets/sprites/caldera/cd_barb.png',
  './assets/sprites/caldera/cd_hotcat.png',
  './assets/sprites/caldera/cd_ember.png',
  './assets/sprites/caldera/cd_malachite.png',
  './assets/sprites/caldera/cd_obsidian.png',
  './assets/sprites/caldera/cd_vent.png',
  './assets/sprites/caldera/cd_magma.png',
  './assets/sprites/caldera/cd_geyser.png',
  './assets/sprites/caldera/cd_pele.png',
  './assets/sprites/caldera/cd_namaka.png',
  './assets/sprites/caldera/cd_king_yobi.png',
  './assets/sprites/abyss/ab_bone.png',
  './assets/sprites/abyss/ab_bottle.png',
  './assets/sprites/abyss/ab_can.png',
  './assets/sprites/abyss/ab_lanternfish.png',
  './assets/sprites/abyss/ab_bristlemouth.png',
  './assets/sprites/abyss/ab_hatchetfish.png',
  './assets/sprites/abyss/ab_snailfish.png',
  './assets/sprites/abyss/ab_cusk.png',
  './assets/sprites/abyss/ab_tripodfish.png',
  './assets/sprites/abyss/ab_viperfish.png',
  './assets/sprites/abyss/ab_dragonfish.png',
  './assets/sprites/abyss/ab_grenadier.png',
  './assets/sprites/abyss/ab_fangtooth.png',
  './assets/sprites/abyss/ab_slickhead.png',
  './assets/sprites/abyss/ab_anglerfish.png',
  './assets/sprites/abyss/ab_gulper.png',
  './assets/sprites/abyss/ab_chimaera.png',
  './assets/sprites/abyss/ab_frilledshark.png',
  './assets/sprites/abyss/ab_goblin.png',
  './assets/sprites/abyss/ab_manta.png',
  './assets/sprites/abyss/ab_starcarrier.png',
  './assets/sprites/abyss/ab_endless.png',
  './assets/sprites/abyss/ab_king_nyx.png',
  './assets/sprites/world-root/wr_shield.png',
  './assets/sprites/world-root/wr_can.png',
  './assets/sprites/world-root/wr_root.png',
  './assets/sprites/world-root/wr_herring.png',
  './assets/sprites/world-root/wr_capelin.png',
  './assets/sprites/world-root/wr_lumpsucker.png',
  './assets/sprites/world-root/wr_plaice.png',
  './assets/sprites/world-root/wr_whiting.png',
  './assets/sprites/world-root/wr_goby.png',
  './assets/sprites/world-root/wr_cod.png',
  './assets/sprites/world-root/wr_salmon.png',
  './assets/sprites/world-root/wr_wolffish.png',
  './assets/sprites/world-root/wr_turbot.png',
  './assets/sprites/world-root/wr_spurdog.png',
  './assets/sprites/world-root/wr_halibut.png',
  './assets/sprites/world-root/wr_ray.png',
  './assets/sprites/world-root/wr_eel.png',
  './assets/sprites/world-root/wr_lump.png',
  './assets/sprites/world-root/wr_nidhogg.png',
  './assets/sprites/world-root/wr_lyngbakr.png',
  './assets/sprites/world-root/wr_loki.png',
  './assets/sprites/world-root/wr_mead.png',
  './assets/sprites/world-root/wr_king_jormungandr.png',
  './assets/sprites/duat/du_shard.png',
  './assets/sprites/duat/du_can.png',
  './assets/sprites/duat/du_reed.png',
  './assets/sprites/duat/du_tilapia.png',
  './assets/sprites/duat/du_mormyrus.png',
  './assets/sprites/duat/du_barbel.png',
  './assets/sprites/duat/du_elephant.png',
  './assets/sprites/duat/du_catlet.png',
  './assets/sprites/duat/du_puffer.png',
  './assets/sprites/duat/du_perch.png',
  './assets/sprites/duat/du_bichir.png',
  './assets/sprites/duat/du_synodontis.png',
  './assets/sprites/duat/du_tigerfish.png',
  './assets/sprites/duat/du_lates.png',
  './assets/sprites/duat/du_electric.png',
  './assets/sprites/duat/du_lapis.png',
  './assets/sprites/duat/du_ray.png',
  './assets/sprites/duat/du_moon.png',
  './assets/sprites/duat/du_ammit.png',
  './assets/sprites/duat/du_bennu.png',
  './assets/sprites/duat/du_sobek.png',
  './assets/sprites/duat/du_wadjet.png',
  './assets/sprites/duat/du_king_osiris.png',
  './assets/sprites/cavern/cv_dripstone.png',
  './assets/sprites/cavern/cv_can.png',
  './assets/sprites/cavern/cv_ladder.png',
  './assets/sprites/cavern/cv_blindloach.png',
  './assets/sprites/cavern/cv_whitegoby.png',
  './assets/sprites/cavern/cv_cavecarp.png',
  './assets/sprites/cavern/cv_translucent.png',
  './assets/sprites/cavern/cv_flatfin.png',
  './assets/sprites/cavern/cv_mudsucker.png',
  './assets/sprites/cavern/cv_barbel.png',
  './assets/sprites/cavern/cv_paleeel.png',
  './assets/sprites/cavern/cv_swimless.png',
  './assets/sprites/cavern/cv_needle.png',
  './assets/sprites/cavern/cv_platefin.png',
  './assets/sprites/cavern/cv_redgill.png',
  './assets/sprites/cavern/cv_jadecarp.png',
  './assets/sprites/cavern/cv_longfin.png',
  './assets/sprites/cavern/cv_slowgrow.png',
  './assets/sprites/cavern/cv_armored.png',
  './assets/sprites/cavern/cv_dripeater.png',
  './assets/sprites/cavern/cv_silentfin.png',
  './assets/sprites/cavern/cv_relict.png',
  './assets/sprites/cavern/cv_king_chosoku.png',
  './assets/sprites/dawn-port/dp_porthole.png',
  './assets/sprites/dawn-port/dp_can.png',
  './assets/sprites/dawn-port/dp_plank.png',
  './assets/sprites/dawn-port/dp_tyregoby.png',
  './assets/sprites/dawn-port/dp_pipeblenny.png',
  './assets/sprites/dawn-port/dp_rustsculpin.png',
  './assets/sprites/dawn-port/dp_bilgesprat.png',
  './assets/sprites/dawn-port/dp_bottlecardinal.png',
  './assets/sprites/dawn-port/dp_platefin.png',
  './assets/sprites/dawn-port/dp_hoseeel.png',
  './assets/sprites/dawn-port/dp_containergrouper.png',
  './assets/sprites/dawn-port/dp_ladderbass.png',
  './assets/sprites/dawn-port/dp_dieselmullet.png',
  './assets/sprites/dawn-port/dp_anchorbream.png',
  './assets/sprites/dawn-port/dp_signalsnapper.png',
  './assets/sprites/dawn-port/dp_hazardtrigger.png',
  './assets/sprites/dawn-port/dp_redleadconger.png',
  './assets/sprites/dawn-port/dp_bluecabin.png',
  './assets/sprites/dawn-port/dp_boilerray.png',
  './assets/sprites/dawn-port/dp_holdgrouper.png',
  './assets/sprites/dawn-port/dp_cabinguard.png',
  './assets/sprites/dawn-port/dp_chainconger.png',
  './assets/sprites/dawn-port/dp_king_sunrise.png',
  './assets/sprites/maple-keep/mk_kawara.png',
  './assets/sprites/maple-keep/mk_hairpin.png',
  './assets/sprites/maple-keep/mk_leafnet.png',
  './assets/sprites/maple-keep/mk_medaka.png',
  './assets/sprites/maple-keep/mk_moroko.png',
  './assets/sprites/maple-keep/mk_motsugo.png',
  './assets/sprites/maple-keep/mk_goby.png',
  './assets/sprites/maple-keep/mk_crucian.png',
  './assets/sprites/maple-keep/mk_dojo.png',
  './assets/sprites/maple-keep/mk_dace.png',
  './assets/sprites/maple-keep/mk_ayu.png',
  './assets/sprites/maple-keep/mk_catfish.png',
  './assets/sprites/maple-keep/mk_maplekoi.png',
  './assets/sprites/maple-keep/mk_eel.png',
  './assets/sprites/maple-keep/mk_masu.png',
  './assets/sprites/maple-keep/mk_castlebream.png',
  './assets/sprites/maple-keep/mk_coppertrout.png',
  './assets/sprites/maple-keep/mk_stonepike.png',
  './assets/sprites/maple-keep/mk_crimsonkoi.png',
  './assets/sprites/maple-keep/mk_armorcarp.png',
  './assets/sprites/maple-keep/mk_wall_eel.png',
  './assets/sprites/maple-keep/mk_shachihoko.png',
  './assets/sprites/maple-keep/mk_sunsettrout.png',
  './assets/sprites/maple-keep/mk_king_momijigari.png',
  './assets/sprites/fox-springs/fs_yunohana.png',
  './assets/sprites/fox-springs/fs_ema.png',
  './assets/sprites/fox-springs/fs_geta.png',
  './assets/sprites/fox-springs/fs_onsenminnow.png',
  './assets/sprites/fox-springs/fs_smelt.png',
  './assets/sprites/fox-springs/fs_sculpin.png',
  './assets/sprites/fox-springs/fs_dojo.png',
  './assets/sprites/fox-springs/fs_bitterling.png',
  './assets/sprites/fox-springs/fs_goby.png',
  './assets/sprites/fox-springs/fs_yamame.png',
  './assets/sprites/fox-springs/fs_iwana.png',
  './assets/sprites/fox-springs/fs_rainbow.png',
  './assets/sprites/fox-springs/fs_masu.png',
  './assets/sprites/fox-springs/fs_burbot.png',
  './assets/sprites/fox-springs/fs_redchar.png',
  './assets/sprites/fox-springs/fs_silverkoi.png',
  './assets/sprites/fox-springs/fs_snoweel.png',
  './assets/sprites/fox-springs/fs_salamander.png',
  './assets/sprites/fox-springs/fs_steamtrout.png',
  './assets/sprites/fox-springs/fs_crystalcarp.png',
  './assets/sprites/fox-springs/fs_ninetailkoi.png',
  './assets/sprites/fox-springs/fs_moonshadow.png',
  './assets/sprites/fox-springs/fs_king_hakugin.png',
  './assets/scenes/mist-lake-background.png',
  './assets/scenes/mist-lake-thumbnail.png',
  './assets/scenes/garden-pond-background.png',
  './assets/scenes/garden-pond-thumbnail.png',
  './assets/scenes/rapids-background.png',
  './assets/scenes/rapids-thumbnail.png',
  './assets/scenes/sunset-fjord-background.png',
  './assets/scenes/sunset-fjord-thumbnail.png',
  './assets/scenes/coral-reef-background.png',
  './assets/scenes/coral-reef-thumbnail.png',
  './assets/scenes/sakura-shrine-background.png',
  './assets/scenes/sakura-shrine-thumbnail.png',
  './assets/scenes/tide-flat-background.png',
  './assets/scenes/tide-flat-thumbnail.png',
  './assets/scenes/frost-lake-background.png',
  './assets/scenes/frost-lake-thumbnail.png',
  './assets/scenes/fall-pool-background.png',
  './assets/scenes/fall-pool-thumbnail.png',
  './assets/scenes/lotus-river-background.png',
  './assets/scenes/lotus-river-thumbnail.png',
  './assets/scenes/caldera-background.png',
  './assets/scenes/caldera-thumbnail.png',
  './assets/scenes/abyss-background.png',
  './assets/scenes/abyss-thumbnail.png',
  './assets/scenes/world-root-background.png',
  './assets/scenes/world-root-thumbnail.png',
  './assets/scenes/duat-background.png',
  './assets/scenes/duat-thumbnail.png',
  './assets/scenes/cavern-background.png',
  './assets/scenes/cavern-thumbnail.png',
  './assets/scenes/dawn-port-background.png',
  './assets/scenes/dawn-port-thumbnail.png',
  './assets/scenes/maple-keep-background.png',
  './assets/scenes/maple-keep-thumbnail.png',
  './assets/scenes/fox-springs-background.png',
  './assets/scenes/fox-springs-thumbnail.png',
  './assets/scenes/sword-pool-background.png',
  './assets/scenes/sword-pool-thumbnail.png',
  './assets/scenes/dunhuang-spring-background.png',
  './assets/scenes/dunhuang-spring-thumbnail.png',
  './assets/sprites/sword-pool/sp_brokenblade.png',
  './assets/sprites/sword-pool/sp_bambutag.png',
  './assets/sprites/sword-pool/sp_gourd.png',
  './assets/sprites/sword-pool/sp_bitterling.png',
  './assets/sprites/sword-pool/sp_stonegoby.png',
  './assets/sprites/sword-pool/sp_bamboominnow.png',
  './assets/sprites/sword-pool/sp_brookloach.png',
  './assets/sprites/sword-pool/sp_silvercrucian.png',
  './assets/sprites/sword-pool/sp_dace.png',
  './assets/sprites/sword-pool/sp_ayu.png',
  './assets/sprites/sword-pool/sp_yamame.png',
  './assets/sprites/sword-pool/sp_jadetrout.png',
  './assets/sprites/sword-pool/sp_greeneel.png',
  './assets/sprites/sword-pool/sp_bladecat.png',
  './assets/sprites/sword-pool/sp_armorcarp.png',
  './assets/sprites/sword-pool/sp_swordtrout.png',
  './assets/sprites/sword-pool/sp_misteel.png',
  './assets/sprites/sword-pool/sp_cranefin.png',
  './assets/sprites/sword-pool/sp_bloodjade.png',
  './assets/sprites/sword-pool/sp_shadowblade.png',
  './assets/sprites/sword-pool/sp_heavensword.png',
  './assets/sprites/sword-pool/sp_drunktrout.png',
  './assets/sprites/sword-pool/sp_king_wuqiao.png',
  './assets/sprites/dunhuang-spring/dh_silkfrag.png',
  './assets/sprites/dunhuang-spring/dh_lampcup.png',
  './assets/sprites/dunhuang-spring/dh_pipapeg.png',
  './assets/sprites/dunhuang-spring/dh_oasisminnow.png',
  './assets/sprites/dunhuang-spring/dh_sandgoby.png',
  './assets/sprites/dunhuang-spring/dh_mooncrucian.png',
  './assets/sprites/dunhuang-spring/dh_reedloach.png',
  './assets/sprites/dunhuang-spring/dh_giltbitter.png',
  './assets/sprites/dunhuang-spring/dh_starbarb.png',
  './assets/sprites/dunhuang-spring/dh_bowfish.png',
  './assets/sprites/dunhuang-spring/dh_pupfish.png',
  './assets/sprites/dunhuang-spring/dh_jadedace.png',
  './assets/sprites/dunhuang-spring/dh_cavecat.png',
  './assets/sprites/dunhuang-spring/dh_silkroadkoi.png',
  './assets/sprites/dunhuang-spring/dh_amberpuffer.png',
  './assets/sprites/dunhuang-spring/dh_apsarafish.png',
  './assets/sprites/dunhuang-spring/dh_muralkoi.png',
  './assets/sprites/dunhuang-spring/dh_crescenteel.png',
  './assets/sprites/dunhuang-spring/dh_ninedeer.png',
  './assets/sprites/dunhuang-spring/dh_whirlfish.png',
  './assets/sprites/dunhuang-spring/dh_silkribbon.png',
  './assets/sprites/dunhuang-spring/dh_thousandlamp.png',
  './assets/sprites/dunhuang-spring/dh_king_jialing.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './icons/apple-touch-icon-180.png',
  './icons/favicon-32.png'
];

/* ---------- 安裝：預先快取所有資源 ---------- */
self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE)
      // 個別 add，單一檔案失敗不會讓整包 addAll 掛掉
      .then(function (c) {
        return Promise.all(ASSETS.map(function (url) {
          return c.add(new Request(url, { cache: 'reload' })).catch(function (err) {
            console.warn('[sw] 預先快取失敗：', url, err);
          });
        }));
      })
      .then(function () { return self.skipWaiting(); })
  );
});

/* ---------- 啟用：清掉舊版本快取 ---------- */
self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys()
      .then(function (keys) {
        return Promise.all(keys.map(function (k) {
          if (k !== CACHE && k.indexOf('fishing-') === 0) return caches.delete(k);
        }));
      })
      .then(function () { return self.clients.claim(); })
  );
});

/* ---------- 取用策略 ----------

   程式碼類（html / js / css / webmanifest）→ network-first
     GitHub Pages 送的是 Cache-Control: max-age=600，瀏覽器的 HTTP 快取會把檔案
     留住 10 分鐘。若這裡用一般的 fetch()，即使 SW 想抓新版也可能被 HTTP 快取攔下來
     回舊檔。所以一律用 cache:'no-cache' 強制跟伺服器對 ETag（命中就是 304，很便宜）。
     這讓「推上去 → 重載一次」就會拿到新版，不必等 10 分鐘也不必重載兩次。

   圖片類 → cache-first
     圖示幾乎不會變，而且是位元組大宗，沒必要每次都對伺服器問。
     真的換圖時把 VERSION 加一，install 階段會強制重抓。
*/

const CODE_RE = /\.(?:html|js|css|webmanifest)$/i;

function isCodeAsset(url) {
  return url.pathname.endsWith('/') || CODE_RE.test(url.pathname);
}

// 強制向伺服器驗證的 fetch（繞過瀏覽器 HTTP 快取，但仍走 ETag 協商）
function fetchFresh(url) {
  return fetch(new Request(url, { cache: 'no-cache', credentials: 'same-origin' }));
}

function timeoutAfter(ms) {
  return new Promise(function (_, reject) {
    setTimeout(function () { reject(new Error('network timeout')); }, ms);
  });
}

function putInCache(req, res) {
  if (res && res.status === 200) {
    const copy = res.clone();
    caches.open(CACHE).then(function (c) { c.put(req, copy); });
  }
  return res;
}

self.addEventListener('fetch', function (e) {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // 外部資源不插手（本專案其實也沒有）

  const navigate = req.mode === 'navigate';

  if (navigate || isCodeAsset(url)) {
    e.respondWith(
      Promise.race([fetchFresh(req.url), timeoutAfter(NET_TIMEOUT)])
        .then(function (res) { return putInCache(req, res); })
        .catch(function () {
          // 離線或逾時：回快取；導覽請求另外退回 index.html
          return caches.match(req).then(function (cached) {
            if (cached) return cached;
            if (navigate) {
              return caches.match('./index.html').then(function (r) {
                return r || caches.match('./');
              });
            }
            return Response.error();
          });
        })
    );
    return;
  }

  // 圖片等靜態資產：cache-first
  e.respondWith(
    caches.match(req).then(function (cached) {
      if (cached) return cached;
      return fetch(req).then(function (res) { return putInCache(req, res); });
    })
  );
});

/* ---------- 讓頁面能主動要求立刻套用新版 ---------- */
self.addEventListener('message', function (e) {
  if (e.data === 'skipWaiting') self.skipWaiting();
});
